# Generated by Django 4.1.3 on 2023-03-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_friend_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
